---
animations:
  talking:
    - gifs/gtalking_bg.gif
    - gifs/talking_bg.gif
    - gifs/talking2_bg.gif
    - gifs/talking3_bg.gif
    - gifs/ctalking_bg.gif
  waving:
    - gifs/waving_bg.gif
  scary:
    - gifs/scary_bg.gif
  surprised:
    - gifs/surprised_bg.gif
  lovely:
    - gifs/lovely_bg.gif
  happy:
    - gifs/happy_bg.gif
    - gifs/happy2_bg.gif
  hello:
    - gifs/hello_bg.gif
  interesting:
    - gifs/interesting_bg.gif
    - gifs/cool_bg.gif
  looking:
    - gifs/looking_bg.gif
  pointing:
    - gifs/pointing_bg.gif
  dancing:
    - gifs/xdancing_bg.gif
    - gifs/dancing2_bg.gif
    - gifs/dancing_bg.gif
    - gifs/singing_bg.gif
    - gifs/jump_bg.gif
  waiting:
    - gifs/waiting_bg.gif
  walk-on:
    - gifs/walk-on.gif
  walk-off:
    - gifs/walk-off.gif
triggers:
  - regex: '\b(?:hello|greet\w+|wav(?:ing|es?))\b'
    animations:
      - hello
      - waving
  - regex: '\b(?:point|that)\b'
    animations:
      - pointing
  - regex: '\b(?:scar\w+|creep\w*|fright\w*|spook\w*)\b'
    animations:
      - scary
      - surprised
  - regex: '\b(?:love|cute|nice|like)\b'
    animations:
      - lovely
  - regex: '\b(?:interest\w*|think|thought|wonder\w*)\b'
    animations:
      - interesting
  - regex: '\b(?:happy|cheer\w*|inspir\w*)\b'
    animations:
      - happy
buttons:
  - label: Wave
    animations:
      - hello
  - label: Look
    animations:
      - looking
  - label: Dance
    animations:
      - dancing
  - label: Wait
    animations:
      - waiting
system:
  waiting:
    animations:
      - waiting
